from content.assert_exception import divide

print(divide(2))